apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    volumeMounts:
    - mountPath: /opt/nginx/conf
      name: conf
  - name: reloader
    image: config-reloader:1.2.3
    volumeMounts:
    - mountPath: /opt/nginx/conf
      name: conf
  volumes:
  - name: conf
    configMap:
      name: conf
